platform :ios, '13.0'
source 'https://github.com/cocoapods/specs.git'

target 'SampleApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SocureSdkDemo
    pod 'SocureDeviceRisk', '~> 4.1.0'
    pod 'Alamofire'
end
