platform :ios, '12.4'

target 'SampleApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SocureSdkDemo
    pod 'DeviceRisk', :git => 'git@github.com:socure-inc/socure-sigmadevice-sdk-ios.git'
    pod 'Alamofire'
end
