platform :ios, '12.4'
source 'https //github.com/cocoapods/specs.git'

target 'SampleApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SocureSdkDemo
    pod 'SocureDeviceRisk', '~> 1.1.0'
    pod 'Alamofire'
end
